# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 12:11
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)])),
                ('last_name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=255)),
                ('age_group', models.SmallIntegerField(choices=[(1, 'Adult(21+)'), (2, 'Teenager'), (3, 'Child'), (0, 'Infant/Toddler')], default=1)),
                ('email', models.EmailField(max_length=254)),
                ('relationship', models.SmallIntegerField(choices=[(1, 'Bride Family'), (2, 'Groom Family'), (3, 'Bride Friend'), (4, 'Groom Friend'), (5, 'Mutual Friend'), (0, 'Other')], default=0)),
                ('visibility', models.SmallIntegerField()),
                ('tier', models.SmallIntegerField(default=10)),
                ('position', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('zip', localflavor.us.models.USZipCodeField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_guests', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest_list.Guest')),
                ('suggested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_guests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('hashtag', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('budget', models.IntegerField()),
                ('max_guests', models.IntegerField()),
                ('event_date', models.DateTimeField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bride_in', to=settings.AUTH_USER_MODEL)),
                ('groom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groom_in', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeddingParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest_list.Household'),
        ),
        migrations.AddField(
            model_name='guest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guest',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest_list.Wedding'),
        ),
    ]
